version: '3.7'

services:
    webserver:
        image: nginx:alpine
        container_name: projeto1-nginx
        working_dir: /app
        volumes:
            - ./:/app
            - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 2233:80

    php-fpm:
        build: .docker/php-fpm
        container_name: projeto1_php74
        working_dir: /app
        expose:
            - 9000
        volumes:
            - ./:/app
